service: cvs-tsk-enquiry-evl-file-push
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-s3-local
provider:
  name: aws
  runtime: nodejs14.x

functions:
  evlFilePush:
    handler: src/handler/s3Event.handler
    events:
      - s3:
          bucket: evl-bucket
          event: s3:ObjectCreated:*

custom:
  serverless-offline:
    port: 3014
  s3:
    host: localhost
    port: 4569
