AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  S3EventFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/handler/s3Event.handler
      Runtime: nodejs14.x
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - src/handler/s3Event.ts

  SrcBucket:
    Type: AWS::S3::Bucket

Outputs:
  S3EventFunction:
    Description: 'S3 Event Lambda Function ARN'
    Value: !GetAtt S3EventFunction.Arn
