export enum EventLogging {
  ENQ_FEED_FILE_PUSH_INIT = 'ENQ_FEED_FILE_PUSH_INITIATED',
  ENQ_FEED_FILE_PUSH_SUCCESS = 'ENQ_FEED_FILE_PUSH_SUCCESSFUL',
  ENQ_FEED_FILE_PUSH_FAILURE = 'ENQ_FEED_FILE_PUSH_FAILED',
}
